export const authConstants = {
  LOGIN_LOADING: "LOGIN_LOADING",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  // REGISTER
  REGISTER_LOADING: "REGISTER_LOADING",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",

  // Logout
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
};
