export const postConstants = {
  CREATE_POST_LOADING: "CREATE_POST_LOADING",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_FAILURE: "CREATE_POST_FAILURE",
  // getpost
  GET_ALL_POST: "GET_ALL_POST",
  GET_ALL_POST_SUCCESS: "GET_ALL_POST_SUCCESS",
  GET_ALL_POST_FAILURE: "GET_ALL_POST_FAILURE",
};
